on: [push]

name: R1

jobs:


  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure CLI Action
      uses: Azure/cli@v1.0.7
    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
        enable-AzPSSession: true 
        
    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          Get-AzVM -ResourceGroupName "ResourceGroup11"
        azPSVersion: "latest"
